a = int(input("Enter first number: "))
b = int(input("Enter second number: "))
print("Addition:", a + b)
a = int(input("Enter first number: "))
b = int(input("Enter second number: "))
print("Subtraction:", a - b)
a = int(input("Enter first number: "))
b = int(input("Enter second number: "))
print("Multiplication:", a * b)
a = int(input("Enter first number: "))
b = int(input("Enter second number: "))
print("Division:", a / b)
